### ISSUE TITLE
Raccoon Gang (5/20)

### ISSUE THREAD

**Issue by adamstankiewicz** [openedx/paragon#1289]
**Merged**

* [x] https://github.com/openedx/paragon/pull/1263
* [x] https://github.com/openedx/paragon/pull/1288
* [x] https://github.com/openedx/paragon/pull/1218
* [x] https://github.com/openedx/paragon/pull/1120

**Reviewed**
* [ ] https://github.com/openedx/paragon/pull/1287/

**Under Review**
* [ ] https://github.com/openedx/paragon/pull/1100

**Tasks**

* [x] https://github.com/openedx/paragon/issues/1301
* [x] https://github.com/openedx/paragon/issues/1302
* [x] https://github.com/openedx/paragon/issues/1303
* [x] https://github.com/openedx/paragon/issues/1304
* [x] https://github.com/openedx/paragon/issues/1305
* [x] https://github.com/openedx/paragon/issues/1306
* [x] https://github.com/openedx/paragon/issues/1307
* [ ] https://github.com/openedx/paragon/issues/1308
* [ ] https://github.com/openedx/paragon/issues/1309
* [x] ~https://openedx.atlassian.net/browse/PAR-816 (fix icon in Dropdown)~
  * [x] Looks like this was fixed already via [this PR](https://github.com/openedx/paragon/pull/1287) 🎉
