### ISSUE TITLE
Ensure consuming projects install `@edx/brand` as the `@edx/brand-openedx` package by default

### ISSUE THREAD

**Issue by adamstankiewicz** [openedx/paragon#2240]
There was a recent question posed in the Open edX frontend working group Slack channel:

> The gradebook upstream repo https://github.com/openedx/frontend-app-gradebook depends on the [edx.org](http://edx.org/) branding package (https://github.com/edx/brand-edx.org). Can this be used without problem, even if it does not depend on the package: https://github.com/openedx/brand-openedx?

The reporter mentioned their colleague went through all MFEs and noticed the only MFE without the `brand-openedx` package installed by default is `frontend-app-gradebook`.

At a higher level, many 2U/edX engineers who work on MFEs only want to run their apps using the `brand-edx.org` theme so their local environment matches what they will see on stage/production. To do this, consumers often install `@edx/brand-edx.org` as the default theme, and forget to change it back to the default, open-source friendly `@edx/brand-openedx` theme before committing/pushing.

In theory, we may also be able to encourage consumers to override the `@edx/brand` package via `module.config.js` instead. We should check to see whether `module.config.js` works with `@edx/brand` overrides, too.

It's also worth mentioning some MFEs get around this by defining  `install-theme`, `start:with-theme`, and `build:with-theme` NPM scripts that overrides the default `@edx/brand` package via a custom brand package through the `THEME` environment variable ([source](https://github.com/openedx/frontend-app-learner-portal-enterprise/blob/8771ef448901e890cdc96d42a535fab88a65fa6f/package.json#L91)). This solution as implemented still hardcodes `@edx/brand-edx.org` as the custom theme, though, which is not ideal.

I believe we could adapt these `install-theme`, `start:with-theme`, `build:with-theme` NPM scripts to be more generic and avoid hardcoding `@edx/brand-edx.org` anywhere in the repos by relying on consuming to pass `THEME="@edx/brand-edx.org"` themselves when running `npm run start:with-theme` or `npm run build:with-theme` (e.g., `THEME="@edx/brand-edx.org" npm run start:with-theme`.

```[tasklist]
### Acceptance Criteria
- [x] Consider whether there's a possible technical solution that would allow consumers of the Paragon and `@edx/brand` packages to run the MFE locally with a custom `@edx/brand` package installed (e.g., `@edx/brand-edx.org`).
- [x] If a technical solution to allow consumers to run/build their MFEs during local development without modifying the default installed `@edx/brand-openedx` package, standardize on this format across all consuming projects where relevant.
- [x] Consider whether this could be a command as part of a Paragon CLI tool (e.g., https://github.com/openedx/paragon/issues/2242), where no manual modifications would be needed to repos?
```

**Comment by monteri** [comment]
https://github.com/openedx/paragon/pull/2460

**Comment by viktorrusakov** [comment]
We decided to implement this via CLI command and adding npm script to the consuming MFE, the progress is tracked in #2831
