### ISSUE TITLE
[Playground] "Copy URL" in playground header and Segment events

### ISSUE THREAD

**Issue by adamstankiewicz** [openedx/paragon#2260]
Using a `StatefulButton`, implement a mechanism to copy the current URL in the Paragon Playground from the header. Co-locate the "Leave feedback" and "Copy URL" buttons on the right side of the header.

<img width="899" alt="image" src="https://user-images.githubusercontent.com/2828721/236364511-bd846e4a-26df-483d-a38e-3370b5d32e5b.png">

```[tasklist]
### Tasks
- [ ] Add "Copy URL" tertiary button to the playground header, aligned to the right with a `ContentCopy` icon.
- [ ] Upon clicking "Copy URL", change the button text to "Copied!" and show a `Check` icon, and copy the current URL to clipboard such that users can quickly share it with others. A Segment event should be dispatched to track the click, following the convention of `openedx.ui.paragon.docs.*`.
- [ ] Move the "Leave feedback" hyperlink to the right side of the header, to left of the "Copy URL" button.
- [ ] Add a Segment event on click of the "Leave feedback" hyperlink.
```
