### ISSUE TITLE
[design tokens] Release `@edx/frontend-platform` as alpha version

### ISSUE THREAD

**Issue by adamstankiewicz** [openedx/paragon#2269]
We have an alpha version of `@edx/paragon` and `@edx/brand-edx.org` supporting design tokens, CSS variables, and already compiled CSS.

There is a draft solution in `@edx/frontend-platform` ([PR](https://github.com/openedx/frontend-platform/pull/440)) to build a mechanism to inject the new, compiled Paragon CSS files from a CDN URL via configuration into an MFE.

In order to ease QA, we should release this as an alpha release similar to the other packages.

```[tasklist]
### Tasks
- [ ] Resolve merge conflicts on the [PR](https://github.com/openedx/frontend-platform/pull/440).
- [ ] Update PR / associated ADR to ensure it reflects current decisions.
- [ ] Address [bug report](https://github.com/openedx/frontend-platform/pull/440#issuecomment-1523803353).
- [ ] Ensure `@edx/frontend-platform` may be released as an alpha pre-release version via semantic-release.
```

**Comment by brian-smith-tcril** [comment]
Design tokens support is in https://github.com/openedx/frontend-platform/releases/tag/v8.0.0
