### ISSUE TITLE
[BD-46] Border-radius of the Button component with the small size

### ISSUE THREAD

**Issue by PKulkoRaccoonGang** [openedx/paragon#2550]
Buttons of different sizes have different outline radius

![image](https://github.com/openedx/paragon/assets/93188219/3fb3a8b2-0e07-43e7-b592-9f7abead1828)

![Screenshot 2023-08-16 at 3 48 00 PM](https://github.com/openedx/paragon/assets/93188219/179cfb57-f94e-4988-9ca1-a3ee785c5873)

```[tasklist]
### Tasks
- [ ] Update the border radius on the focus outline radius.
- [ ] Verify the 2px offset for the focus outline.
- [ ] Outline-primary border to `$primary-500`.
```

**Comment by PKulkoRaccoonGang** [comment]
PR: https://github.com/openedx/paragon/pull/2786
