### ISSUE TITLE
Resource for a11y color contrast validation

### ISSUE THREAD

**Issue by adamstankiewicz** [openedx/paragon#2647]
* https://webaim.org/resources/contrastchecker/

--- 

```[tasklist]
### Tasks
- [ ] Bring proposal to Paragon Working Group.
- [ ] Either link to existing tool as shown above from new "Accessibility" foundation page, and/or implement custom similar tool as docs site page.
- [ ] Refer to prior PWG meeting agenda notes from Jeff/Matthew about the content for standalone "Accessibility" foundation page.
```

**Comment by PKulkoRaccoonGang** [comment]
PR: https://github.com/openedx/paragon/pull/2726

**Comment by PKulkoRaccoonGang** [comment]
**UPD**:
- from the PWG there is a decision to put Contrast checker under the Tools item and make the link for the https://webaim.org/resources/contrastchecker
