### ISSUE TITLE
Duplicate calls to `onChange` in `Form.RadioSet` and `Form.CheckboxSet`

### ISSUE THREAD

**Issue by adamstankiewicz** [openedx/paragon#2683]
## Bugs

Both `Form.RadioSet` and `Form.CheckboxSet` appear to have a duplicate call to the given `onChange` prop when the user's radio / checkbox selection(s) change.

<img width="1531" alt="image" src="https://github.com/openedx/paragon/assets/2828721/bb4c2064-a10e-4058-8be5-d0cf79fc68f0">

[Paragon Playground demo](https://paragon-openedx.netlify.app/playground?code=N4Igxg9gJgpiBcJgApkEoAEBeAfB4AOgHYYaREDOALhgNoBuAhgDYCuMANBhTFQGot2AXWwZWPAMpVGVGMgDkAcwBOMGEXloA3MVLlqGABaMiUZjADCxoopii7ufLtJkIlCOYB0zCIoXWzS2tbAEIwzR0SFx5%2BQTkYT2llWypPJjYYbWcAX0jSVSpWZRJkZ1IAHgAxCGUAW08AcWUIVgAHHDKXKpr6gBlGACMYZhwAdUMASzBDDAsPGoB%2BcoB6arrPfqGRzoq1%2BoAlRigJiAleHZciRlqYLAJweeUKe4vSNysTWyxgAPMPmxg2VeGHS7G%2BoMBFw6URcXT2nkOxwgILidxAqig9xw%2BxgUBW8MRJ2hsNh3XWhORELRKjURCxTVp%2BJ6CKOROBZIOrMpqPuAwyWIAQhkmeSucSSbtmRSURk0WAAJ4me4YY4UQbmKA4CyKogizlI8Wk1ZSrlnKiGjB6xrNNrirJEbJodDZEAcEBUQwwG4UBC0EC4gAanhqihAQjdAHcJlAPT74LQAOwANgAHEJskA)

```[tasklist]
### Tasks
- [ ] Ensure `Form.RadioSet`'s `onChange` prop is not called more than once.
- [ ] Ensure `Form.CheckboxSet`'s `onChange` prop is not called more than once.
- [ ] Ensure the fix is backported to v20 (e.g., see https://openedx.atlassian.net/wiki/spaces/FEDX/pages/3755868171/How+to+backport+a+change+to+a+previous+version+with+semantic-release+for+JS+libraries) for MFEs that are currently blocked on upgrading to Paragon v21 due to unrelated peer dependency issues.
```

**Comment by PKulkoRaccoonGang** [comment]
PR: https://github.com/openedx/paragon/pull/2705

**Comment by viktorrusakov** [comment]
@adamstankiewicz The fix is available in both `v20.46.3` and `v21.5.3`
