### ISSUE TITLE
Paragon CLI version

### ISSUE THREAD

**Issue by PKulkoRaccoonGang** [openedx/paragon#2870]
In popular CLI interfaces, you will notice that it is possible to view the version of the CLI being used. It would be an interesting idea to add the ability to view the Paragon CLI version using the `paragon -v` (`paragon --version`) command.

For example:
<img width="509" alt="image" src="https://github.com/openedx/paragon/assets/93188219/ef2a96cd-6698-4da9-94ac-de752a63ad43">

```[tasklist]
### Tasks
- [ ] Ensure that after entering the `paragon -v` (`paragon --version`) command the Paragon CLI version is displayed
- [ ] Update supporting documentation (`paragon help` command)
- [ ] Ensure that the functionality works both locally in Paragon and in MFE consumers
```

**Comment by PKulkoRaccoonGang** [comment]
PR: https://github.com/openedx/paragon/pull/2921
