### ISSUE TITLE
`DataTable`'s "Select all..." label in `BaseSelectionStatus` shows incorrect counts

### ISSUE THREAD

**Issue by adamstankiewicz** [openedx/paragon#2872]
## Bugs

There appears to be a bug/regression related to `DataTable` and the "Select all" label in the `BaseSelectionStatus` component, introduced by [this PR](https://github.com/openedx/paragon/pull/2020/files), which seemed to separately resolve a different bug.

As seen on the [Paragon documentation site](https://paragon-openedx.netlify.app/components/datatable/#paginated-selection), when selecting a row using the `DataTable.ControlledSelect*` sub-components, the "Select all..." label incorrectly says "Select all **3**" when there are **7** rows total.

<img width="905" alt="image" src="https://github.com/openedx/paragon/assets/2828721/b4ea87ff-f3ed-4c2e-a2b6-7705abd8d18e">

I believe the issue is related to this line:

```jsx
const filteredItems = filteredRows?.length || itemCount;
```

It appears that even without any filters applied, `filteredRows` comes back with an array containing the rows for current page, preventing the `itemCount` from being shown.

Adjusting the logic to include `hasAppliedFilters` resolves this particular issue:

```jsx
const filteredItems = (hasAppliedFilters && filteredRows?.length) || itemCount;
```

However, it does appear that when a filter is applied, the "Select all..." count is still not quite correct when using the `DataTable.ControlledSelect*` components. For example, this below table has 60 rows total without any filters ("Select all 60" ✅ ); with a filter applied for "Status" column, there are now 55 rows total (`itemCount`) but it would state "Select all 25" ⛔ (since the visible page has 25 rows):

<img width="1075" alt="image" src="https://github.com/openedx/paragon/assets/2828721/b6df8eda-1cb0-427e-8c58-28319397d345">

```[tasklist]
### Tasks
- [ ] When using the `DataTable.ControlledSelect*` subcomponents, ensure that when no filters are applied, the "Select all..." label contains the `itemCount` for the `DataTable`. It should indicate the total number of rows across the entire table.
- [ ] When using the `DataTable.ControlledSelect*` subcomponents, ensure that when there are filters applied, the "Select all..." label still contains the `itemCount` for the table.
- [ ] When using the default `DataTable` subcomponents, ensure that when no filters are applied, the "Select all..." label contains the `itemCount` for the `DataTable`.  It should indicate the total number of rows across the entire table.
- [ ] When using the default `DataTable` subcomponents,  ensure that when there are filters applied, the "Select all..." label contains the total number of `filteredRows` across all pages.
```

**Comment by PKulkoRaccoonGang** [comment]
PR: https://github.com/openedx/paragon/pull/2929
