### ISSUE TITLE
Update paragon alpha with the current state of non-alpha paragon

### ISSUE THREAD

**Issue by chris1tapia** [openedx/paragon#3058]
```[tasklist]
### Tasks
- [ ] https://github.com/openedx/paragon/issues/3072
- [ ] https://github.com/openedx/paragon/issues/3073
- [ ] https://github.com/openedx/paragon/issues/3074
```

**Comment by PKulkoRaccoonGang** [comment]
PRs:
- https://github.com/openedx/paragon/pull/3044
- https://github.com/openedx/paragon/pull/3048
- https://github.com/openedx/paragon/pull/3052
- https://github.com/openedx/paragon/pull/3051
- https://github.com/openedx/paragon/pull/3056
