### ISSUE TITLE
[bug]: Hardcoded size value of action Buttons in the Alert component

### ISSUE THREAD

**Issue by PKulkoRaccoonGang** [openedx/paragon#3205]
## Bugs

In [the Alert component](https://paragon-openedx.netlify.app/components/alert/), the user does not have the ability to pass the size for the action buttons (the value is not passed in props, but is [statically hardcoded ](https://github.com/openedx/paragon/blob/master/src/Alert/index.jsx#L27)in the internal implementation of the component).

<img width="566" alt="image" src="https://github.com/user-attachments/assets/1de67983-843a-4978-9f07-de2d07045e6a">

[Example](https://paragon-openedx.netlify.app/playground?code=N4Igxg9gJgpiBcJgApkEoAEBeAfB4AOgHYYYBOMALgK5knLGkA8AggDYxmWOkYBuAQzIBLAUUpYCIYUQBmEKT1ICwlYRCIBnLMADaS3kwBC1SpQ0ZNwgF4xJIALZQpOABIw2bCEwD0Jsxo4ADQGALoAvgZQwpoOMVYARhwGYF6aMAAyAgke9gAiMXGamookvBoAwml2KDCYuPgYkFoQHAB0XgDmyADkqRDpUD1BGHUA3Bjhkzw4BgAqABYxGMsCGFIy8lIYAhxcGADuwpQLwD0YPZFlzOyclG0ZMgDWGAsUsvYAxC5iowAeAgcAAcOBg2M9fLcuA9njg2hgAOLCPgwFaUHZNcFgF7CWQYACeEGoBnBTxgbR4kL2lFmZTQY2I4TQ6HCIHCQA)

## Improvements

Since Paragon provides the ability to resize buttons, it would be great to provide this for the Alert component as well.

```[tasklist]
### Tasks
- [ ] Ensure that inside the Alert component the user has the ability to change the size of the action buttons.
- [ ] Ensure that in other components where it is possible to pass the button size, this size is displayed correctly.
- [ ] Ensure that the Alert component (and possibly other components) are displayed correctly on mobile screens with increased button size (`'sm', 'md', 'lg', 'inline'`)
```

**Comment by brian-smith-tcril** [comment]
Possibly a design decision - current size works for buttons at small (320px) viewport widths
