### ISSUE TITLE
Add types for CardBody component

### ISSUE THREAD

**Issue by PKulkoRaccoonGang** [openedx/paragon#3332]
In the [PR replacing the Bootstrap BaseCard component](https://github.com/openedx/paragon/pull/3318/files), we have already begun rewriting the Card component in TypeScript. Currently, the BaseCard component contains @ts-ignore comments, which can be eliminated by converting the CardBody component to TypeScript.

```[tasklist]
### Tasks
- [ ] Convert the CardBody component to TypeScript.
- [ ] Test the updated BaseCard and CardBody components to verify type safety and functionality.
- [ ] Update relevant documentation, if necessary.
```
